version: '3.4'

services:
  php:
    environment:
      - APP_ENV=dev
      - APP_DEBUG=1
    build:
      context: ./
      target: sftpl_php_dev
    depends_on:
      - db
    volumes:
      - ./docker/php/conf.d/php.dev.ini:/usr/local/etc/php/conf.d/99-php-custom.ini
      - ./docker/apache/vhosts:/etc/apache2/sites-enabled
      - ./:/srv/api:cached
      - ./var:/srv/api/var:rw

  adminer:
    image: adminer
    depends_on:
      - db
    ports:
      - "8080:8080"

  db:
    ports:
      - "3306:3306"
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_ROOT_PASSWORD=api
      - MYSQL_DATABASE=api
    volumes:
      - sftpl-db-data:/var/lib/mysql

  mailhog:
    # do not use in production!
    image: mailhog/mailhog:latest
    environment:
      - MH_STORAGE=maildir
    # volumes:
    #   - ./docker/mailhog/maildir:/maildir:rw,delegated
    ports:
      - "8025:8025"

volumes:
  sftpl-db-data: {}
