authentication_token:
    path: /authentication_token
    methods: ['POST']

api_login_check:
    path: /api/login_check

gesdinet_jwt_refresh_token:
    path:       /api/token/refresh
    controller: gesdinet.jwtrefreshtoken::refresh
    methods: ['POST']

dashboard:
    path: /admin
    controller: App\Controller\Admin\DashboardController::index
